exclude: (^static/ | ^templates/)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ["--config", "flake8.cfg"]
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.2
  hooks:
  - id: bandit
    args: ["-c", "bandit.yaml"]
- repo: https://github.com/google/yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    additional_dependencies: [toml]
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
